##
# IMPORTANT:
#   Currently this `docker-compose.yml` is used only in the local environments.
#   Make sure it is synced with `.github/workflows/ci.yml`.
##

version: "3.9"

##
# IMPORTANT:
#   Docker compose creates a shared network for its containers.
#   As a result, ports from the right side are only accessible between containers.
#   At the same time, ports from left side are only accessible by host.
#   For example:
#
#     redis:
#       ports:
#         - 6380:6379
#
#   To access Redis from container - use `redis://redis:6379`.
#   To access Redis from host - use `redis://localost:6380`.
#
services:
  ##
  # NOTE: Redis image exposes 6379 by default. In order to use diffrent port the `redis-server` command is modified.
  # - https://github.com/docker-library/redis/blob/f623bf8a6fef29b1459a29ff9f852c0f88d76b5a/7.2/debian/Dockerfile#L152
  # - https://medium.com/@dulanjanalakmal/simplifying-redis-cluster-deployment-with-docker-compose-d6f9abebd31b
  # - https://redis.io/docs/latest/operate/oss_and_stack/management/config
  #
  action_cable_redis:
    container_name: ${PROJECT_NAME}_action_cable_redis
    image: redis:${ACTION_CABLE_REDIS_VERSION}
    volumes:
      - ../../docker/development/volumes/action_cable_redis:/var/lib/redis/data
    command: redis-server --port 6380

  ##
  # - https://github.com/SeleniumHQ/docker-selenium
  # - https://hub.docker.com/r/selenium/standalone-chrome
  #
  chrome:
    container_name: ${PROJECT_NAME}_chrome
    image: selenium/standalone-chrome:${CHROME_VERSION}-chromedriver-${CHROMEDRIVER_VERSION}
    ports:
      ##
      # NOTE: Open `http://localhost:${HOST_OS_CHROME_HTTP_PORT}`. Password is `secret`.
      #
      - "${HOST_OS_CHROME_HTTP_PORT}:${CHROME_HTTP_PORT}"
      - "${HOST_OS_CHROME_PORT}:${CHROME_PORT}"
      ##
      # NOTE: Open `vnc://localhost:${HOST_OS_CHROME_VNC_PORT}`. Password is `secret`.
      #
      - "${HOST_OS_CHROME_VNC_PORT}:${CHROME_VNC_PORT}"
    volumes:
      - /dev/shm:/dev/shm

  postgres:
    container_name: ${PROJECT_NAME}_postgres
    image: postgres:${POSTGRES_VERSION}
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - ../../docker/development/volumes/postgres:/var/lib/postgresql/data

  rails:
    build:
      args:
        - RUBY_VERSION
        - NODE_VERSION
      context: ../..
      dockerfile: ./docker/development/rails/Dockerfile
    container_name: ${PROJECT_NAME}_rails
    depends_on:
      - action_cable_redis
      - postgres
    environment:
      ACTION_CABLE_REDIS_URL: ${ACTION_CABLE_REDIS_URL}
      CHROME_HOST: ${CHROME_HOST}
      CHROME_PORT: ${CHROME_PORT}
      POSTGRES_HOST: ${POSTGRES_HOST}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USERNAME: ${POSTGRES_USERNAME}
      POSTGRES_VERSION: ${POSTGRES_VERSION}
      PROJECT_NAME: ${PROJECT_NAME}
      RUBY_VERSION: ${RUBY_VERSION}
      TURNIP_RAILS_PORT: ${TURNIP_RAILS_PORT}
    stdin_open: true
    tty: true
    volumes:
      - ../..:/project
