version: '3'

##
# NOTE: `open` tasks only navigate/open apps. They are NOT running any other commands.
##

##
# TODO: Global preconditions are imitated using YAML anchors. Replace anchors once native support added.
# - https://github.com/go-task/task/issues/294
#
<<: &from-host-os
  - sh: '[ "${IN_DOCKER_CONTAINER}" != "true" ]'
    msg: This task can be invoked only from the host operating system (https://www.ibm.com/cloud/learn/containerization)

##
# IMPORTANT: All tasks listed in this file should be executed from the root folder.
# - https://taskfile.dev/usage/#task-directory
#
tasks:
  ##
  # NOTE: Annotate (aka AnnotateModels) options.
  # - https://github.com/ctran/annotate_models/blob/develop/lib/annotate/parser.rb
  #
  # NOTE: Same as `task annotate`, but without `--frozen` option.
  # IMPORTANT: Must be kept in sync with `task annotate`.
  #
  annotate:
    cmds:
      - bundle exec annotate --models --position-in-class=bottom --format=bare --exclude=tests

  ##
  # NOTE: Same as `task annotate`, but with `--frozen` option for linting.
  # IMPORTANT: Must be kept in sync with `task annotate`.
  #
  annotate:lint:
    cmds:
      - bundle exec annotate --models --position-in-class=bottom --format=bare --exclude=tests --frozen

  bundle:
    cmds:
      - bundle

  ##
  # - https://guides.rubyonrails.org/active_record_migrations.html#resetting-the-database
  #
  db:reset:
    cmds:
      - bundle exec rails db:reset

  ##
  # NOTE: Rake task that allows to verify whether schema.rb and migration files have been correctly committed.
  # - https://github.com/kufu/db_schema_checker
  #
  db:schema:lint:
    cmds:
      - RAILS_ENV=test bundle exec rails db:migrate:reset:check

  ##
  # NOTE: `docker compose run` automatically builds image if is not built yet.
  #
  docker:bash:
    cmds:
      - docker compose -f docker/development/docker-compose.yml run --rm rails bash
    interactive: true
    preconditions:
      *from-host-os

  ##
  # NOTE:
  #   `task install` is executed during image build process.
  #   But it is impossible to have access to the volumes during the image build process.
  #   So `Gemfile` changes are NOT persisted inside `Gemfile.lock`.
  #   That is why `task install` is executed for the second time by `docker compose run` since it has access to volumes.
  #   This add more minutes to `task docker:build`, but eliminates the time required to debug unmodified `Gemfile.lock` issues.
  #
  # NOTE:
  #   `docker compose up` builds all images listed in the `docker-compose.yml` and then starts all containers.
  #   This is too resource heavy most of the time, that is why `docker compose build` and `docker compose run` with Docker Compose `depends_on` are used instead.
  #
  docker:build:
    cmds:
      - docker compose -f docker/development/docker-compose.yml build rails
      - docker compose -f docker/development/docker-compose.yml run --rm rails bash -c "task install"
    preconditions:
      *from-host-os

  docker:bundle:
    cmds:
      - docker compose -f docker/development/docker-compose.yml run --rm rails bash -c 'task bundle'
    interactive: true
    preconditions:
      *from-host-os

  docker:chrome:build:
    cmds:
      - docker-compose -f docker/development/docker-compose.yml up --build --remove-orphans chrome
    preconditions:
      *from-host-os

  docker:chrome:http:open:
    cmds:
      - open http://localhost:{{.HOST_OS_CHROME_HTTP_PORT}}
    preconditions:
      *from-host-os
    requires:
      vars: [HOST_OS_CHROME_HTTP_PORT]

  docker:chrome:logs:
    cmds:
      - docker logs --follow {{.PROJECT_NAME}}_chrome
    preconditions:
      *from-host-os
    requires:
      vars: [PROJECT_NAME]

  docker:chrome:vnc:open:
    cmds:
      - open vnc://localhost:{{.HOST_OS_CHROME_VNC_PORT}}
    preconditions:
      *from-host-os
    requires:
      vars: [HOST_OS_CHROME_VNC_PORT]

  docker:down:
    cmds:
      - docker-compose -f docker/development/docker-compose.yml down
    preconditions:
      *from-host-os

  ##
  # NOTE: Importmap for Rails.
  # - https://github.com/rails/importmap-rails?tab=readme-ov-file#using-npm-packages-via-javascript-cdns
  #
  docker:importmap:pin:
    cmds:
      - docker compose -f docker/development/docker-compose.yml run --rm rails bash -c 'task importmap:pin -- {{.CLI_ARGS}}'
    preconditions:
      *from-host-os

  ##
  # NOTE: Importmap for Rails.
  # - https://github.com/rails/importmap-rails?tab=readme-ov-file#using-npm-packages-via-javascript-cdns
  #
  docker:importmap:unpin:
    cmds:
      - docker compose -f docker/development/docker-compose.yml run --rm rails bash -c 'task importmap:unpin -- {{.CLI_ARGS}}'
    preconditions:
      *from-host-os

  docker:lint:
    cmds:
      - docker compose -f docker/development/docker-compose.yml run --rm rails bash -c 'AUTOCORRECT={{.AUTOCORRECT}} task lint'
    preconditions:
      *from-host-os

  docker:rspec:
    cmds:
      - docker compose -f docker/development/docker-compose.yml run --rm rails bash -c 'task rspec'
    interactive: true
    preconditions:
      *from-host-os

  docker:rubocop:
    cmds:
      - docker compose -f docker/development/docker-compose.yml run --rm rails bash -c 'AUTOCORRECT={{.AUTOCORRECT}} task rubocop'
    interactive: true
    preconditions:
      *from-host-os

  docker:server:
    cmds:
      - rm tmp/pids/server.pid 2> /dev/null || true
      ##
      # NOTE: `-b 0.0.0.0` makes Rails server accessible from all hosts.
      # - https://stackoverflow.com/a/29084070/12201472
      #
      - |
        docker compose \
          -f docker/development/docker-compose.yml \
          run \
          --rm \
          --publish {{.RAILS_PORT}}:{{.RAILS_PORT}} \
          rails \
          bash -c '
            bundle exec rails db:create \
              && bundle exec rails db:migrate \
              && bundle exec rails server --port {{.RAILS_PORT}} -b 0.0.0.0
          '
    interactive: true
    preconditions:
      *from-host-os
    requires:
      vars: [RAILS_PORT]

  docker:server:open:
    cmds:
      - open -na "Google Chrome" --args --new-window --incognito "http://localhost:{{.RAILS_PORT}}"
    requires:
      vars: [RAILS_PORT]

  docker:standardjs:
    cmds:
      - docker compose -f docker/development/docker-compose.yml run --rm rails bash -c 'AUTOCORRECT={{.AUTOCORRECT}} task standardjs'
    preconditions:
      *from-host-os

  docker:stylelint:
    cmds:
      - docker compose -f docker/development/docker-compose.yml run --rm rails bash -c 'AUTOCORRECT={{.AUTOCORRECT}} task stylelint'
    preconditions:
      *from-host-os

  docker:turnip:
    cmds:
      - |
        docker compose \
          -f docker/development/docker-compose.yml \
          run \
          --rm \
          --publish {{.TURNIP_RAILS_PORT}}:{{.TURNIP_RAILS_PORT}} \
          rails \
          bash -c 'task turnip'
    interactive: true
    preconditions:
      *from-host-os
    requires:
      vars: [TURNIP_RAILS_PORT]

  docker:yarn:
    cmds:
      - docker compose -f docker/development/docker-compose.yml run --rm rails bash -c 'task yarn'
    preconditions:
      *from-host-os

  ##
  # NOTE: Dev only command.
  # NOTE: macOS specific command.
  # NOTE: Used by `tmuxinator`.
  #
  docker:start:
    cmds:
      - open -a Docker

  ##
  # NOTE: Dev only command.
  #
  editor:open:
    cmds:
      - code .

  ##
  # Generate Entity-Relationship Diagrams for Rails applications.
  # - https://github.com/voormedia/rails-erd
  #
  # TODO: Fix `Failed: NoMethodError: undefined method `direct_descendants' for class ActionText::Record`.
  # - https://github.com/voormedia/rails-erd/issues/377
  #
  erd:
    cmds:
      - bundle exec erd

  ##
  # NOTE: Usage examples.
  #   task standardjs
  #   AUTOCORRECT=true task standardjs
  #
  standardjs:
    cmds:
      - yarn run standard {{.AUTOCORRECT_SUFFIX}} {{.CLI_ARGS}}
    vars:
      AUTOCORRECT_SUFFIX:
        sh: ruby -e 'puts "--fix" if ENV["AUTOCORRECT"] == "true"'

  ##
  # NOTE: Usage examples.
  #   task stylelint
  #   # Lint all CSS files.
  #
  #   AUTOCORRECT=true task stylelint
  #   # Autoformat all CSS files.
  #
  stylelint:
    cmds:
      - yarn run stylelint --config ./linters/.stylelintrc.js {{.AUTOCORRECT_SUFFIX}} **/*.css
    vars:
      AUTOCORRECT_SUFFIX:
        sh: ruby -e 'puts "--fix" if ENV["AUTOCORRECT"] == "true"'

  ##
  # NOTE: Dev only command.
  # NOTE: macOS specific command.
  #
  github:open:
    cmds:
      - open -na "Google Chrome" --args --new-window --incognito "https://github.com/marian13/blueprinter"

  ##
  # NOTE: Importmap for Rails.
  # - https://github.com/rails/importmap-rails?tab=readme-ov-file#using-npm-packages-via-javascript-cdns
  #
  # NOTE: Examples.
  #   task importmap:pin -- axios
  #   task importmap:pin -- axios --from=jsdelivr
  #
  importmap:pin:
    cmds:
      - ./bin/importmap pin {{.CLI_ARGS}}

  ##
  # NOTE: Importmap for Rails.
  # - https://github.com/rails/importmap-rails?tab=readme-ov-file#using-npm-packages-via-javascript-cdns
  #
  # NOTE: Examples.
  #   task importmap:unpin -- axios
  #   task importmap:unpin -- axios --from=jsdelivr
  #
  importmap:unpin:
    cmds:
      - ./bin/importmap unpin {{.CLI_ARGS}}

  install:
    cmds:
      - task bundle
      - task yarn

  lint:
    cmds:
      - AUTOCORRECT={{.AUTOCORRECT}} task stylelint
      - AUTOCORRECT={{.AUTOCORRECT}} task standardjs
      - AUTOCORRECT={{.AUTOCORRECT}} task rubocop
      - AUTOCORRECT={{.AUTOCORRECT}} task db:schema:lint
      - AUTOCORRECT={{.AUTOCORRECT}} task annotate:lint

  rspec:
    cmds:
      - |
        bundle exec rspec \
          --require rails_helper \
          --format progress \
          --exclude-pattern "./spec/features/**/*" \
          spec

  ##
  # NOTE: Usage examples.
  #   task rubocop
  #   AUTOCORRECT=true task rubocop
  #
  rubocop:
    cmds:
      - bundle exec rubocop --config .rubocop.yml {{.AUTOCORRECT_SUFFIX}} {{.CLI_ARGS}}
    vars:
      AUTOCORRECT_SUFFIX:
        sh: ruby -e 'puts "-A" if ENV["AUTOCORRECT"] == "true"'

  server:logs:test:
    cmds:
      - touch log/test.log && tail -f log/test.log

  ##
  # NOTE: Dev only command.
  #
  tmuxinator:start:
    cmds:
      - direnv exec . tmuxinator start blueprinter --project-config=.dev/.tmuxinator.yml

  ##
  # NOTE: Dev only command.
  #
  tmuxinator:stop:
    cmds:
      - direnv exec . tmuxinator stop blueprinter --project-config=.dev/.tmuxinator.yml

  ##
  # NOTE: RSpec supports multiple formatters.
  # - https://github.com/rspec/rspec-core/commit/a5f9ffd270ff8d450d9460f14b269b48685c4567
  #
  # NOTE: Turnip HTML formatter.
  # - https://github.com/gongo/turnip_formatter
  #
  # TODO: Cucumber-like logs for Turnip.
  # - https://github.com/jnicklas/turnip?tab=readme-ov-file#rspec-custom-formatters
  #
  turnip:
    cmds:
      - |
        bundle exec rspec \
          --require turnip/rspec \
          --require turnip_formatter \
          --format progress \
          --format RSpecTurnipFormatter \
          --out tmp/turnip_report.html \
          spec/features
    interactive: true
    requires:
      vars: [TURNIP_RAILS_PORT]

  turnip:open:
    cmds:
      - open tmp/turnip_report.html

  yarn:
    cmds:
      - yarn
