version: '3'

##
# IMPORTANT: All tasks listed in this file should be executed from the root folder.
# - https://taskfile.dev/usage/#task-directory
#
tasks:
  ##
  # NOTE: Dev only command.
  #
  editor:open:
    cmds:
      - code .

  ##
  # NOTE: Dev only command.
  # NOTE: macOS specific command.
  #
  github:open:
    cmds:
      - open -na "Google Chrome" --args --new-window --incognito "https://github.com/marian13/blueprinter"

  ##
  # NOTE: Dev only command.
  #
  tmuxinator:start:
    cmds:
      - tmuxinator start blueprinter --project-config=.dev/.tmuxinator.yml
