##
# - https://userdocs.convenientservice.org/tldr
#
ConvenientService::Dependencies.require_has_j_send_result_params_validations_using_active_model_validations
ConvenientService::Dependencies.require_assigns_attributes_in_constructor_using_dry_initializer
ConvenientService::Dependencies.require_rescues_result_unhandled_exceptions
ConvenientService::Dependencies.require_amazing_print_inspect if Rails.env.local?
