default: &default
  adapter: postgresql
  encoding: unicode
  host: <%= ENV.fetch("POSTGRES_HOST") %>
  username: <%= ENV.fetch("POSTGRES_USERNAME") %>
  password: <%= ENV.fetch("POSTGRES_PASSWORD") %>
  pool: 5

development:
  <<: *default
  database: <%= ENV.fetch("PROJECT_NAME") %>_development

test:
  <<: *default
  database: <%= ENV.fetch("PROJECT_NAME") %>_test
