##
# NOTE: Prefer to use `ENV.fetch` to get ENV variables values.
# - https://ruby-doc.org/core-2.7.1/ENV.html#method-c-fetch
# - https://github.com/rubocop/rubocop-rails/issues/306
#
default: &default
  adapter: postgresql
  encoding: unicode
  host: <%= ENV.fetch("POSTGRES_HOST") %>
  username: <%= ENV.fetch("POSTGRES_USERNAME") %>
  password: <%= ENV.fetch("POSTGRES_PASSWORD") %>
  pool: 5

development:
  <<: *default
  database: <%= ENV.fetch("PROJECT_NAME") %>_development

test:
  <<: *default
  database: <%= ENV.fetch("PROJECT_NAME") %>_test
