##
# NOTE: Tmuxinator config options.
# - https://github.com/tmuxinator/tmuxinator#create-a-project
#
name: blueprinter
root: .

on_project_start:
  - task editor:open
  - task docker:start

on_project_stop:
  - task docker:down

windows:
  - main:
      layout: even-vertical
      root: .
      panes:
        - RAILS_PORT=8400 task docker:server
        - task docker:bash
        - history -s "task github:open"
  - turnip:
      layout: even-vertical
      root: .
      panes:
        - history -s "task docker:chrome:build"
        - history -s "task docker:chrome:logs"
        - history -s "task docker:chrome:vnc:open"
        - task server:logs:test
        - history -s "task docker:turnip"
